CREATE TABLE users (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     email VARCHAR(100) UNIQUE NOT NULL,
     name VARCHAR(100) NOT NULL,
     created_at TIMESTAMP NOT NULL
);

CREATE TABLE categories (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(100) UNIQUE NOT NULL,
     description VARCHAR(500),
     created_at TIMESTAMP NOT NULL
);

CREATE TABLE requests (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     title VARCHAR(150) NOT NULL,
     description VARCHAR(2000) NOT NULL,
     status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
     author_id BIGINT NOT NULL,
     category_id BIGINT NOT NULL,
     created_at TIMESTAMP NOT NULL,
     updated_at TIMESTAMP,
     FOREIGN KEY (author_id) REFERENCES users (id),
     FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE comments (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     text VARCHAR(1000) NOT NULL,
     author_id BIGINT NOT NULL,
     request_id BIGINT NOT NULL,
     created_at TIMESTAMP NOT NULL,
     updated_at TIMESTAMP,
     FOREIGN KEY (author_id) REFERENCES users (id),
     FOREIGN KEY (request_id) REFERENCES requests (id)
);

CREATE TABLE status_history (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     request_id BIGINT NOT NULL,
     old_status VARCHAR(20),
     new_status VARCHAR(20) NOT NULL,
     changed_at TIMESTAMP NOT NULL,
     FOREIGN KEY (request_id) REFERENCES requests (id)
);